version: 2.1

jobs:
  install:
    docker:
      - image: cimg/node:18.18.0
    working_directory: ~/war_house_back
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test:
    docker:
      - image: cimg/node:18.18.0
    working_directory: ~/war_house_back
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: npm test

  trigger_ci_cd:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Trigger CI/CD Pipeline After Successful Tests
          command: |
            curl -X POST https://circleci.com/api/v2/project/gh/Abdel1117/war_house_ci/pipeline \
            -H "Circle-Token: $CIRCLE_TOKEN" \
              command: |
              if [ "$CIRCLE_BRANCH" = "dev" ]; then
                curl -X POST https://circleci.com/api/v2/project/gh/Abdel1117/war_house_ci/pipeline \
                -H "Circle-Token: $CIRCLE_TOKEN" \
                -H "Content-Type: application/json" \
                -d '{"branch": "dev"}'
              elif [ "$CIRCLE_BRANCH" = "prod" ]; then
                curl -X POST https://circleci.com/api/v2/project/gh/Abdel1117/war_house_ci/pipeline \
                -H "Circle-Token: $CIRCLE_TOKEN" \
                -H "Content-Type: application/json" \
                -d '{"branch": "prod"}'
              fi

  build_and_deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Clone Front and Back Repos
          command: |
            git clone https://github.com/Abdel1117/War-house.git ../War_House_Front
            git clone https://github.com/Abdel1117/War_house_back.git ../War_House_Back
      - run:
          name: Build Docker Images
          command: |
            docker-compose -f ../War_House_Back/docker-compose.yml build
      - run:
          name: Deploy Services
          command: |
            docker-compose -f ../War_House_Back/docker-compose.yml up -d

workflows:
  version: 2
  ci_cd_pipeline:
    jobs:
      - install
      - test:
          requires:
            - install
      - trigger_ci_cd:
          requires:
            - test
          filters:
            branches:
              only:
                - dev
                - main
      - build_and_deploy:
          requires:
            - trigger_ci_cd
          filters:
            branches:
              only: main
