version: 2.1

jobs:
  install:
    docker:
      - image: cimg/node:18.18.0
    working_directory: ~/war_house_back
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test:
    docker:
      - image: cimg/node:18.18.0
    working_directory: ~/war_house_back
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Trigger CI/CD Pipeline After Successful Tests
          command: |
            if [ "$CIRCLE_BRANCH" == "dev" ] || [ "$CIRCLE_BRANCH" == "main" ]; then
              if [ "$CIRCLE_JOB" == "test" ] && [ "$CIRCLE_TEST_EXIT_CODE" == "0" ]; then
                curl -X POST https://circleci.com/api/v2/project/gh/user/ci-cd-repo/pipeline \
                -H "Circle-Token: $CIRCLE_TOKEN" \
                -H "Content-Type: application/json" \
                -d '{"branch": "$CIRCLE_BRANCH"}'
              fi
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install
      - test:
          requires:
            - install
